### Agenda
- Python Revision
- Numpy Library - Arrays
- Matplotlib  - Visualization
- Pandas - Dataframe
- Seaborn and pandas
- plotly library + dash(framework using flask)

### **Installing and Using Python with Different IDEs**

#### **Step 1. Installing Python**
1. Visit [Python's official website](https://www.python.org/downloads/).
2. Download the latest version for your OS (Windows, macOS, Linux).
3. Run the installer and check the option **"Add Python to PATH"** before installation.
4. Verify installation:
   - Open a terminal or command prompt.
   - Type `python --version` to confirm installation.

---
#### **Step 2. Using Python in VS Code**
**Installation**
1. Download and install [VS Code](https://code.visualstudio.com/Download).
2. Install the Python extension:
   - Open VS Code.
   - Go to **Extensions (`Ctrl+Shift+X`)** and search for **Python**.
   - Install the Python extension by Microsoft.

**Using Python**
1. Open VS Code and create a new `.py` file.
2. Write Python code and save the file.
3. Run the script:
   - Open the terminal (`Ctrl+~`).
   - Run `python filename.py`.

---

#### **Alternate option. Using Python in Google Colab**
1. Go to [Google Colab](https://colab.research.google.com/).
2. Click **"New Notebook"**.
3. Write Python code in a cell.
4. Run the cell using **Shift+Enter**.

## Python Revision

#### Python Data Types
<table style="width: 100%; border-collapse: collapse; border: 1px solid #ccc; text-align: left;">
  <tr style="background-color: #050A30; color: white;">
        <th style="border: 1px solid #ccc; padding: 8px;">Category</th>
        <th style="border: 1px solid #ccc; padding: 8px;">Data Type</th>
        <th style="border: 1px solid #ccc; padding: 8px;">Description</th>
        <th style="border: 1px solid #ccc; padding: 8px;">Examples</th>
    </tr>
    <tr>
        <td style="border: 1px solid #ccc; padding: 8px;">Numeric</td>
        <td style="border: 1px solid #ccc; padding: 8px;">int</td>
        <td style="border: 1px solid #ccc; padding: 8px;">Integer, represents whole numbers</td>
        <td style="border: 1px solid #ccc; padding: 8px;">5, -12, 0</td>
    </tr>
    <tr>
        <td style="border: 1px solid #ccc; padding: 8px;">Numeric</td>
        <td style="border: 1px solid #ccc; padding: 8px;">float</td>
        <td style="border: 1px solid #ccc; padding: 8px;">Floating-point, represents real numbers with a decimal</td>
        <td style="border: 1px solid #ccc; padding: 8px;">5.5, -3.14, 0.0</td>
    </tr>
    <tr>
        <td style="border: 1px solid #ccc; padding: 8px;">Numeric</td>
        <td style="border: 1px solid #ccc; padding: 8px;">complex</td>
        <td style="border: 1px solid #ccc; padding: 8px;">Complex number, has real and imaginary parts</td>
        <td style="border: 1px solid #ccc; padding: 8px;">3+5j, -2j</td>
    </tr>
    <tr>
        <td style="border: 1px solid #ccc; padding: 8px;">Sequence</td>
        <td style="border: 1px solid #ccc; padding: 8px;">str</td>
        <td style="border: 1px solid #ccc; padding: 8px;">String, a sequence of Unicode characters</td>
        <td style="border: 1px solid #ccc; padding: 8px;">"hello", 'world'</td>
    </tr>   
    <tr>
        <td style="border: 1px solid #ccc; padding: 8px;">Boolean</td>
        <td style="border: 1px solid #ccc; padding: 8px;">bool</td>
        <td style="border: 1px solid #ccc; padding: 8px;">Represents True or False values</td>
        <td style="border: 1px solid #ccc; padding: 8px;">True, False</td>
    </tr>
    <tr>
        <td style="border: 1px solid #ccc; padding: 8px;">None Type</td>
        <td style="border: 1px solid #ccc; padding: 8px;">NoneType</td>
        <td style="border: 1px solid #ccc; padding: 8px;">Represents the absence of a value or a null value</td>
        <td style="border: 1px solid #ccc; padding: 8px;">None</td>
    </tr>
</table>


In [1]:
name = "Jane"
type(name)

str

In [3]:
name = input("Enter your name - ")
print("Welcome", name)

Enter your name -  George


Welcome George


In [5]:
num1 = int(input("Enter a number - "))
num2 = int(input("Enter a number - "))
num1 + num2

Enter a number -  5
Enter a number -  7


12

#### Python Containers
   
<table style="width: 100%; border-collapse: collapse; border: 1px solid #ccc; text-align: center;">
  <thead>
    <tr style="background-color: #050A30; color: white;">
      <th style="border: 1px solid #ccc; padding: 8px;">Object</th>
      <th style="border: 1px solid #ccc; padding: 8px;">Container Object</th>
      <th style="border: 1px solid #ccc; padding: 8px;">Sequence Type</th>
      <th style="border: 1px solid #ccc; padding: 8px;">Element Type</th>
      <th style="border: 1px solid #ccc; padding: 8px;">Enclosed in</th>
      <th style="border: 1px solid #ccc; padding: 8px;">Immutability</th>
      <th style="border: 1px solid #ccc; padding: 8px;">Duplicates</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="border: 1px solid #ccc; padding: 8px;">str()</td>
      <td style="border: 1px solid #ccc; padding: 8px;">No</td>
      <td style="border: 1px solid #ccc; padding: 8px;">ordered/indexed</td>
      <td style="border: 1px solid #ccc; padding: 8px;">characters</td>
      <td style="border: 1px solid #ccc; padding: 8px;">"" or ''</td>
      <td style="border: 1px solid #ccc; padding: 8px;">Yes</td>
      <td style="border: 1px solid #ccc; padding: 8px;">Yes</td>
    </tr>
    <tr>
      <td style="border: 1px solid #ccc; padding: 8px;">tuple()</td>
      <td style="border: 1px solid #ccc; padding: 8px;">Yes</td>
      <td style="border: 1px solid #ccc; padding: 8px;">ordered/indexed</td>
      <td style="border: 1px solid #ccc; padding: 8px;">mixed data (heterogeneous)</td>
      <td style="border: 1px solid #ccc; padding: 8px;">()</td>
      <td style="border: 1px solid #ccc; padding: 8px;">Yes</td>
      <td style="border: 1px solid #ccc; padding: 8px;">Yes</td>
    </tr>
    <tr>
      <td style="border: 1px solid #ccc; padding: 8px;">list()</td>
      <td style="border: 1px solid #ccc; padding: 8px;">Yes</td>
      <td style="border: 1px solid #ccc; padding: 8px;">ordered/indexed</td>
      <td style="border: 1px solid #ccc; padding: 8px;">mixed data (heterogeneous)</td>
      <td style="border: 1px solid #ccc; padding: 8px;">[]</td>
      <td style="border: 1px solid #ccc; padding: 8px;">No</td>
      <td style="border: 1px solid #ccc; padding: 8px;">Yes</td>
    </tr>
    <tr>
      <td style="border: 1px solid #ccc; padding: 8px;">set()</td>
      <td style="border: 1px solid #ccc; padding: 8px;">Yes</td>
      <td style="border: 1px solid #ccc; padding: 8px;">unordered</td>
      <td style="border: 1px solid #ccc; padding: 8px;">heterogeneous (immutable objects)</td>
      <td style="border: 1px solid #ccc; padding: 8px;">{}</td>
      <td style="border: 1px solid #ccc; padding: 8px;">No</td>
      <td style="border: 1px solid #ccc; padding: 8px;">No</td>
    </tr>
    <tr>
      <td style="border: 1px solid #ccc; padding: 8px;">dict()</td>
      <td style="border: 1px solid #ccc; padding: 8px;">Yes</td>
      <td style="border: 1px solid #ccc; padding: 8px;">unordered</td>
      <td style="border: 1px solid #ccc; padding: 8px;">Key - immutable<br>Value - any type</td>
      <td style="border: 1px solid #ccc; padding: 8px;">{}</td>
      <td style="border: 1px solid #ccc; padding: 8px;">No</td>
      <td style="border: 1px solid #ccc; padding: 8px;">Key - No<br>Value - Yes</td>
    </tr>


In [6]:
tup = (1, 2, 3, 4)
tup[2]

3

In [8]:
lst = [10, 20, 30]
lst

[10, 20, 30]

In [13]:
s = {1, 2, 3, 4, 2}
print(s)

{1, 2, 3, 4}


In [14]:
dct = {1: "Jane", 2 : "George", 3 : "Rosie"}
dct

{1: 'Jane', 2: 'George', 3: 'Rosie'}

###### Ex. WAP to take profit value as input and print if it is profit or loss.

In [17]:
value = int(input("Enter a value - "))
if value < 0 :
    print("Loss")
else :
    print("Profit")

Enter a value -  -20


Loss


###### Ex. WAP to generate numbers from 1-20 and print their summation

In [19]:
total = 0
for i in range(1, 21) :
    total += i
total

210

In [20]:
sum(range(1, 21)) # Note - pass any numeric sequence to sum()

210

###### Ex. Vowels in  string - 

1. WAP to extract all the vowels from a word enter by user
2. Replace all the vowels with `*` in the string

In [21]:
word = input("Enter a word - ").lower()
for ch in word :
    if ch in "aeiou" :
        print(ch)

Enter a word -  singapore


i
a
o
e


In [25]:
word = input("Enter a word - ").lower()
for ch in "aeiou" :
    word = word.replace(ch, "*")
word

Enter a word -  singapore


's*ng*p*r*'

In [32]:
word = "singapore"
obj = str.maketrans("aeiou", "15896")
word.translate(obj)

's8ng1p9r5'

In [34]:
profit = "($1,200)"  # -1200
obj = str.maketrans("(", "-", "$,)")
int(profit.translate(obj))

-1200

###### Ex. WAP to create a list of squares of numbers from 1-10

In [36]:
[i**2 for i in range(1, 11)] # comprehension syntax

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

###### Ex. WAP to sort the given list in desc order - 

In [39]:
names = ["Jack", "Rosie", "George", "Sam"]
sorted(names, reverse=True)

['Sam', 'Rosie', 'Jack', 'George']

In [41]:
sorted(names, key = len )

['Sam', 'Jack', 'Rosie', 'George']

In [42]:
len("Sam")

3

<hr><hr>

## Basics of NumPy
- NumPy - Introduction and Installation
- NumPy - Arrays Data Structure ( 1D, 2D, ND arrays)
- Creating Arrays
- NumPy - Data Types
- Array Attributes
- Creating Arrays – Alternative Ways
- Sub-setting, Slicing and Indexing Arrays
- Operations on Arrays
- Array Manipulation


#### NumPy – Introduction and Installation

- NumPy stands for ‘Numeric Python’
- Used for mathematical and scientific computations
- NumPy array is the most widely used object of the NumPy library

#### Installing numpy

In [ ]:
pip install numpy
pip install pandas
pip install matplotlib
pip install seaborn

#### Importing numpy

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [45]:
pip install numpy  # one time process

Note: you may need to restart the kernel to use updated packages.


ERROR: Invalid requirement: '#'

[notice] A new release of pip is available: 23.2.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [43]:
import numpy as np

### Arrays Data Structure

An `Array` is combination of homogenous data objects and can be indexed across multiple dimensions

#### Arrays are –
- ordered sequence/collection of Homogenous data
- multidimensional
- mutable


#### Creating Arrays – From list/tuple

- `np.array()` is used to create a numpy array from a list


#### Example on 1-D Array

In [46]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

#### Example on 2-D Array

In [47]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### Array Attributes

- Attributes are the features/characteristics of an object that describes the object

- Some of the attributes of the numpy array are:
    - **shape** - Array dimensions
    - **size** - Number of array elements
    - **dtype** - Data type of array elements
    - **ndim** - Number of array dimensions
    - **dtype.name** - Name of data type
    - **astype** - Convert an array to a different type


In [48]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
arr.shape  # - (row, cols)

(3, 4)

In [52]:
arr.size

12

In [53]:
arr.ndim

2

In [54]:
arr.dtype

dtype('int64')

In [55]:
arr.astype(float)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

### Indexing, Slicing and Boolen Indexing

In [56]:
arr = np.random.randint(5, 50, size = 10)
arr

array([37, 40, 28, 45, 31, 16, 12, 19, 36, 30], dtype=int32)

#### 1-D Arrays

###### Ex. Extract first 3 elements

In [57]:
arr[0:3]

array([37, 40, 28], dtype=int32)

###### Ex. Extract last 5 elements

In [58]:
arr[-5 : ]

array([16, 12, 19, 36, 30], dtype=int32)

###### Ex. Extract element at position 2

In [59]:
arr[2]  # indexing

np.int32(28)

###### Ex. Extract elements at index position 2, 5, 9.

In [60]:
arr[[2, 5, 9]]

array([28, 16, 30], dtype=int32)

###### Ex. Extract elements less than 20

In [64]:
arr < 20  # Filtering - generates a bool array

array([False, False, False, False, False,  True,  True,  True, False,
       False])

In [63]:
arr[arr < 20]

array([16, 12, 19], dtype=int32)

### 2-D Arrays

In [65]:
arr = np.random.randint(5, 50, size = (6,4))
arr

array([[39, 29, 32, 19],
       [27, 33, 21, 47],
       [29, 32,  8, 45],
       [35, 31, 19,  9],
       [39, 15, 35, 45],
       [ 6, 34, 22, 23]], dtype=int32)

###### Ex. Extract first 3 rows

In [66]:
arr[0:3]

array([[39, 29, 32, 19],
       [27, 33, 21, 47],
       [29, 32,  8, 45]], dtype=int32)

###### Ex. Extract last 2 rows

In [67]:
arr[-2 :]

array([[39, 15, 35, 45],
       [ 6, 34, 22, 23]], dtype=int32)

###### Ex. Extract column at index 1

In [68]:
arr[ : , 1]  # returns 1D array

array([29, 33, 32, 31, 15, 34], dtype=int32)

###### Ex. Extract row 2 and 3 and column 2 and 3 (index-wise)

In [69]:
arr[2:4, 2:4]

array([[ 8, 45],
       [19,  9]], dtype=int32)

###### Ex. Extract values less than 25

In [70]:
arr[arr < 25]

array([19, 21,  8, 19,  9, 15,  6, 22, 23], dtype=int32)

###### Ex. Identify largest value. Extract values less than half of largest values

In [74]:
arr[arr < np.max(arr)/2]

array([19, 21,  8, 19,  9, 15,  6, 22, 23], dtype=int32)

### Array Operations

#### Arithmetic operations on Arrays -
 - Addition, Substraction, Multiplication, Division, etc.
 - Operations on array and a scalar value
 - Operations between two arrays
 - Matrix Operations - Multiplication(np.dot()), Transpose(np.transpose())


#### Array and Scalar

In [75]:
arr1 = np.random.randint(1,10,size = 5)
arr1

array([1, 5, 9, 4, 3], dtype=int32)

In [76]:
arr1 + 5 # Addition

array([ 6, 10, 14,  9,  8], dtype=int32)

In [77]:
arr1 - 5 # Substraction

array([-4,  0,  4, -1, -2], dtype=int32)

In [78]:
arr1 * 5 # Multiplication

array([ 5, 25, 45, 20, 15], dtype=int32)

In [79]:
arr1 / 5 # Division

array([0.2, 1. , 1.8, 0.8, 0.6])

In [80]:
arr1 // 5 # Floor Division

array([0, 1, 1, 0, 0], dtype=int32)

In [81]:
arr1 % 5 # Modulus

array([1, 0, 4, 4, 3], dtype=int32)

#### Two Arrays

In [82]:
arr1 = np.random.randint(1,10,size = 5)
arr1

array([1, 7, 2, 1, 6], dtype=int32)

In [83]:
arr2 = np.random.randint(1,10,size = 5)
arr2

array([6, 2, 3, 8, 5], dtype=int32)

In [84]:
arr1 + arr2 # Addition

array([ 7,  9,  5,  9, 11], dtype=int32)

In [85]:
arr1 - arr2 # Substraction

array([-5,  5, -1, -7,  1], dtype=int32)

In [86]:
arr1 * arr2 # Multiplication

array([ 6, 14,  6,  8, 30], dtype=int32)

In [87]:
arr1 / arr2 # Division

array([0.16666667, 3.5       , 0.66666667, 0.125     , 1.2       ])

In [88]:
arr1 // arr2 # Floor Division

array([0, 3, 0, 0, 1], dtype=int32)

In [89]:
arr1 % arr2 # Modulus

array([1, 1, 2, 1, 1], dtype=int32)

#### Relational operations on Arrays -
 - ==, !=, <, >, <=, >=
 - Operations on array and a scalar value
 - Operations between two arrays

#### Array and Scalar

In [90]:
arr1 = np.random.randint(1,10,size = 5)
arr1

array([4, 1, 4, 1, 6], dtype=int32)

In [91]:
arr1 == 5

array([False, False, False, False, False])

In [92]:
arr1 != 5

array([ True,  True,  True,  True,  True])

In [93]:
arr1 < 5

array([ True,  True,  True,  True, False])

In [94]:
arr1 > 5

array([False, False, False, False,  True])

In [95]:
arr1 <= 5

array([ True,  True,  True,  True, False])

In [96]:
arr1 >= 5

array([False, False, False, False,  True])

#### Two Arrays

In [97]:
arr1 = np.random.randint(1,10,size = 5)
arr1

array([9, 1, 3, 6, 1], dtype=int32)

In [98]:
arr2 = np.random.randint(1,10,size = 5)
arr2

array([5, 7, 1, 6, 2], dtype=int32)

In [99]:
arr1 == arr2

array([False, False, False,  True, False])

In [100]:
arr1 != arr2

array([ True,  True,  True, False,  True])

In [101]:
arr1 < arr2

array([False,  True, False, False,  True])

In [102]:
arr1 > arr2

array([ True, False,  True, False, False])

In [103]:
arr1 <= arr2

array([False,  True, False,  True,  True])

In [104]:
arr1 >= arr2

array([ True, False,  True,  True, False])

#### Logical operations on Arrays -
 - np.logical_or()
 - np.logical_and()
 - np.logical_not()
 - np.logical_xor()

In [105]:
arr1 = np.random.randint(1,10,size = 5)
arr1

array([5, 2, 6, 4, 6], dtype=int32)

In [106]:
arr2 = np.random.randint(1,10,size = 5)
arr2

array([5, 5, 7, 9, 9], dtype=int32)

In [107]:
np.logical_and(arr1 > 5, arr2 > 5)

array([False, False,  True, False,  True])

In [108]:
np.logical_or(arr1 > 5, arr2 > 5)

array([False, False,  True,  True,  True])

In [109]:
np.logical_not(arr1 > 5)

array([ True,  True, False,  True, False])

In [110]:
np.logical_xor(arr1 > 5, arr2 > 5)

array([False, False, False,  True, False])

#### Set Operations on Arrays

Applicable to 1-D Ararys only

- np.unique() - Find the unique elements of an array.
- np.in1d() - Test whether each element of a 1-D array is also present in a second array.
- np.intersect1d() - Find the intersection of two arrays.
- np.setdiff1d() - Find the set difference of two arrays.
- np.union1d() - Find the union of two arrays.

In [111]:
arr1 = np.random.randint(1, 10, size = 10)
arr1

array([4, 9, 7, 6, 2, 7, 9, 2, 3, 8], dtype=int32)

In [112]:
np.unique(arr1)

array([2, 3, 4, 6, 7, 8, 9], dtype=int32)

In [113]:
np.unique(arr1, return_index= True, return_counts=True)

(array([2, 3, 4, 6, 7, 8, 9], dtype=int32),
 array([4, 8, 0, 3, 2, 9, 1]),
 array([2, 1, 1, 1, 2, 1, 2]))

In [114]:
arr2 = np.random.randint(1, 5, size = 10)
arr2

array([2, 2, 3, 2, 3, 3, 2, 4, 2, 3], dtype=int32)

In [115]:
np.in1d(arr1, arr2)  # depricated in 3.12 onwards

C:\Users\vaide\AppData\Local\Temp\ipykernel_516\2696172370.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(arr1, arr2)  # depricated in 3.12 onwards


array([ True, False, False, False,  True, False, False,  True,  True,
       False])

In [116]:
np.isin(arr1, arr2)  # alternate for in1d()

array([ True, False, False, False,  True, False, False,  True,  True,
       False])

In [117]:
np.union1d(arr1, arr2)

array([2, 3, 4, 6, 7, 8, 9], dtype=int32)

In [118]:
np.intersect1d(arr1, arr2)

array([2, 3, 4], dtype=int32)

###### Ex. WAP to apply 7% service tax to all the values in the array

In [119]:
sales = np.array([200, 400, 300, 250, 550])
sales * 1.07

array([214. , 428. , 321. , 267.5, 588.5])

### Array Functions/Methods

- np.all(), np.any()
- arr.sum()
- arr.min(), arr.max(), arr.argmin(), arr.agrmax()
- np.round()
- np.mean(), np.median(), np.average(), np.percentile()


In [120]:
arr1 = np.random.randint(1, 10, size = 10)
arr1

array([4, 8, 6, 4, 9, 7, 8, 7, 4, 1], dtype=int32)

###### Ex. WAP to check if all the elements in arr are > 5

In [122]:
np.all(arr1 > 5)

np.False_

In [123]:
arr1.min()

np.int32(1)

In [124]:
arr1.argmin()

np.int64(9)

### Array Manipulations

- **Changing Shape** – np.reshape()
- **Adding/Removing Elements** – np.append(), np.insert(), np.delete()
- **Splitting Arrays** – np.hsplit(), np.vsplit(), arr_obj.flatten()
- **Sorting Arrays** - arr_obj.sort(), arr_obj.argsort()

In [125]:
arr = np.arange(1, 13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#### np.reshape()

In [126]:
arr = np.reshape(arr, (4, 3))
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### np.append()

In [127]:
np.append(arr, [10,20,30, 50, 40, 60]) # Flattens the array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 10, 20, 30, 50, 40,
       60])

In [131]:
np.append(arr, np.reshape(np.array([13, 14, 15]), (1, 3)), axis = 0) # axis = 0 denotes row-wise

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [129]:
np.append(arr, np.reshape(np.array([10, 20, 30, 40]), (4, 1)), axis = 1) # axis = 1 denotes col-wise

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20],
       [ 7,  8,  9, 30],
       [10, 11, 12, 40]])

#### np.insert()

In [132]:
arr = np.reshape(np.arange(1,13), (4,3))
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [133]:
np.insert(arr, 1, 5) # Flattens the arr and inserts 5 at index 1

array([ 1,  5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [134]:
np.insert(arr, 1, 5, axis=0) # Inserts [5, 5, 5] as row 1

array([[ 1,  2,  3],
       [ 5,  5,  5],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [135]:
np.insert(arr, 1, 5, axis=1) # Inserts [5, 5, 5, 5] as column 1

array([[ 1,  5,  2,  3],
       [ 4,  5,  5,  6],
       [ 7,  5,  8,  9],
       [10,  5, 11, 12]])

In [136]:
np.insert(arr, 1, [10, 20, 30, 40], axis=1)

array([[ 1, 10,  2,  3],
       [ 4, 20,  5,  6],
       [ 7, 30,  8,  9],
       [10, 40, 11, 12]])

In [137]:
np.insert(arr, 1, [10, 20, 30], axis=0)

array([[ 1,  2,  3],
       [10, 20, 30],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### np.delete()

In [138]:
arr = np.reshape(np.arange(1,13), (4,3))
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [139]:
np.delete(arr, 1) # Flattens the arr and deletes element at index 1

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [140]:
np.delete(arr, 1, axis=0) # deletes row 1

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

In [141]:
np.delete(arr, 1, axis=1) # deletes column 1

array([[ 1,  3],
       [ 4,  6],
       [ 7,  9],
       [10, 12]])

In [142]:
np.delete(arr,[0,2], axis=0) # deletes selected rows

array([[ 4,  5,  6],
       [10, 11, 12]])

In [143]:
np.delete(arr,[0,2], axis=1) # deletes selected columns

array([[ 2],
       [ 5],
       [ 8],
       [11]])

#### np.hsplit(), np.vsplit()

In [144]:
arr = np.reshape(np.arange(1, 25), (6,4))
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [145]:
np.vsplit(arr, 2)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [146]:
np.hsplit(arr, 2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]

In [147]:
arr.shape

(6, 4)

#### flatten()

In [148]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [151]:
arr.flatten() # returns a 1-D array

array([24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,
        7,  6,  5,  4,  3,  2,  1])

In [150]:
arr.flatten(order = "F") # returns a 1-D array

array([ 1,  5,  9, 13, 17, 21,  2,  6, 10, 14, 18, 22,  3,  7, 11, 15, 19,
       23,  4,  8, 12, 16, 20, 24])

In [ ]:
help(arr.flatten)

#### np.sort()

In [164]:
products = np.array(["P1", "P2", "P3", "P4", "P5"])
sales = np.random.randint(200, 600, 5)
sales

array([305, 479, 348, 216, 219], dtype=int32)

In [165]:
np.sort(sales)  # ASC order

array([216, 219, 305, 348, 479], dtype=int32)

In [166]:
np.sort(sales)[::-1]  # DESC order

array([479, 348, 305, 219, 216], dtype=int32)

###### Ex. Sort the products by sales

In [167]:
np.argsort(sales)  # index position of original values in sales arr sorted in ASC order

array([3, 4, 0, 2, 1])

In [168]:
s_ord = np.argsort(sales) 
products[s_ord]

array(['P4', 'P5', 'P1', 'P3', 'P2'], dtype='<U2')

#### Examples on Coffee Shop Data Set

In [199]:
import numpy as np
products = np.array(['Caffe Latte', 'Cappuccino', 'Colombian', 'Darjeeling', 'Decaf Irish Cream', 'Earl Grey', 'Green Tea', 'Lemon', 'Mint', 'Regular Espresso'])
sales = np.array([60014.0, 14068.0, 71060.0, 60014.0, 69925.0, 27711.0, 19231.0, 24873.0, 32825.0, 44109.0])
profits = np.array([17444.0, 5041.0, 28390.0, 20459.0, 23432.0, 7691.0, -2954.0, 7159.0, 10722.0, 14902.0])
target_profits = np.array([15934.0, 4924.0, 31814.0, 19649.0, 24934.0, 8461.0, 7090.0, 7084.0, 10135.0, 16306.0])
target_sales = np.array([48909.0, 13070.0, 80916.0, 57368.0, 66906.0, 30402.0, 18212.0, 21628.0, 27336.0, 42102.0])

###### Ex. How many products are there in the dataset?

In [185]:
sales.size

10

In [186]:
len(sales)

10

###### Ex.  Sales greater than 50,000

In [187]:
sales[sales > 50000]

array([60014., 71060., 60014., 69925.])

###### Ex.  Identify Losses

In [188]:
profits[profits < 0]

array([-2954.])

###### Ex.  Products in loss

In [189]:
products[profits < 0]

array(['Green Tea'], dtype='<U17')

###### Ex.  Product with maximum Sales

In [197]:
products[np.argmax(sales)]

np.str_('Colombian')

In [198]:
products[sales == np.max(sales)]

array(['Colombian'], dtype='<U17')

###### Note - When two max values are present in the array

In [192]:
products = np.array(["P1", "P2", "P3", "P4", "P5"])
sales = np.array([10, 20, 30, 30, 20])

In [193]:
products[np.argmax(sales)]

np.str_('P3')

In [194]:
products[sales == np.max(sales)]

array(['P3', 'P4'], dtype='<U2')

###### Ex. Identify the products meeting the Target Sales

In [202]:
sale_ach = products[sales >= target_sales]
sale_ach

array(['Caffe Latte', 'Cappuccino', 'Darjeeling', 'Decaf Irish Cream',
       'Green Tea', 'Lemon', 'Mint', 'Regular Espresso'], dtype='<U17')

###### Ex. Are the above products meeting their profit target too? If not then display the products.

In [207]:
profit_ach = products[profits >= target_profits]
if np.all(np.isin(sale_ach, profit_ach)):
    print("Yes, all products are also achieveing profit target")
else:
    print("No. These products do not achieve their profit targets - ", np.setdiff1d(sale_ach, profit_ach))

No. These products do not achieve their profit targets -  ['Decaf Irish Cream' 'Green Tea' 'Regular Espresso']


###### Ex. Identify products which are not achieving their profit target. Calculate their target status in percentage. Display the products in DESC order of their percentage status

In [209]:
# Details of the product not achieveing their targets
product_off = products[profits < target_profits]
profit_off = profits[profits < target_profits]
target_off = target_profits[profits < target_profits]

In [221]:
# Calculating percetage of target achievement
percentage = np.round(profit_off/target_off * 100, 2)
# Mark the negavite % as 0
percentage[percentage < 0] = 0
percentage

array([89.24, 93.98, 90.9 ,  0.  , 91.39])

In [222]:
# Sorting the arrays 
s_ord = np.argsort(percentage)[::-1]

In [223]:
for prod, perc in zip(product_off[s_ord], percentage[s_ord]):
    print(f"{prod} has achieved {perc}% of total profits")

Decaf Irish Cream has achieved 93.98% of total profits
Regular Espresso has achieved 91.39% of total profits
Earl Grey has achieved 90.9% of total profits
Colombian has achieved 89.24% of total profits
Green Tea has achieved 0.0% of total profits


In [224]:
product_off

array(['Colombian', 'Decaf Irish Cream', 'Earl Grey', 'Green Tea',
       'Regular Espresso'], dtype='<U17')

In [225]:
percentage

array([89.24, 93.98, 90.9 ,  0.  , 91.39])

In [214]:
list(zip(product_off, percentage))  # Creats a sequence of tuples with values from the lists

[(np.str_('Colombian'), np.float64(89.0)),
 (np.str_('Decaf Irish Cream'), np.float64(94.0)),
 (np.str_('Earl Grey'), np.float64(91.0)),
 (np.str_('Green Tea'), np.float64(0.0)),
 (np.str_('Regular Espresso'), np.float64(91.0))]

<hr><hr>

# Data visualization (Basics)

- Representation of the data in a pictorial or graphical format
- Allow us to get the intuitive understanding of the data
- Helps to visualize the patterns in the data
- Python offers multiple great graphing libraries that come packed with lots of different features.
- Matplotlib: low level, provides lots of freedom
- Pandas Visualization: easy to use interface, built on Matplotlib
- Seaborn: high-level interface, great default styles
- Plotly: can create interactive plots
- Bokeh: used creating interactive visualizations for modern web browsers"

### Primary Objects of matplotlib
<img src = "./images/figure.png" align = left width = 300>
<br><br><br><br><br><br><br><br>

- The [figure] is the overall figure space that can contain one or more plots
- The [axes] is the individual plots that are rendered within the figure

### Anatomy of a figure

<img src = "./images/figure_anatomy.jpg" align = left width = 400>

### Using matplotlib.pyplot library to plot a chart

#### Installing library -

!pip install matplotlib

#### Importing library -

In [1]:
import matplotlib.pyplot as plt

###### Ex. Construct a line chart displaying the daily closing values of Sensex and Nifty throughout the days in September.

In [ ]:
import numpy as np
dates = np.arange('2024-09-01', '2024-10-01', dtype='datetime64[D]')
sensex = np.random.randint(79000, 82000, size = 30)
nifty = np.random.randint(23000, 25000, size = 30)

#### Creating a subplot

### Additional chart types

In [2]:
import numpy as np
products = np.array(['Caffe Latte', 'Cappuccino', 'Colombian', 'Darjeeling', 'Decaf Irish Cream', 'Earl Grey', 'Green Tea', 'Lemon', 'Mint', 'Regular Espresso'])
sales = np.array([52248.0, 14068.0, 71060.0, 60014.0, 69925.0, 27711.0, 19231.0, 24873.0, 32825.0, 44109.0])
profits = np.array([17444.0, 5041.0, 28390.0, 20459.0, 23432.0, 7691.0, -2954.0, 7159.0, 10722.0, 14902.0])
target_profits = np.array([15934.0, 4924.0, 31814.0, 19649.0, 24934.0, 8461.0, 7090.0, 7084.0, 10135.0, 16306.0])
target_sales = np.array([48909.0, 13070.0, 80916.0, 57368.0, 66906.0, 30402.0, 18212.0, 21628.0, 27336.0, 42102.0])

#### Bar chart

###### Ex. Create a bar chart displaying sales for different products. Incorporate the following elements into the chart:

1. Add a title, grid lines, and an average line.
2. Adjust the y-axis ticks to display in thousands.
3. Include annotations for each bar, showing values in thousands.
4. Sort the bars in descending order of sales                     

#### Stacked bar chart

###### Ex. Include profits in the above chart as a stacked bar chart

#### Side by Side Bar Chart

###### Ex. Convert the stacked bar chart into side by side bar chart. Add following changes to the chart - 
1. Adjust the annotations co-ordinates
2. Change color of negative profits to red

#### Bullet chart

###### Ex. Design a bullet chart to illustrate profit target status. Ensure the chart includes the following components:

1. Utilize a horizontal bar chart format.
2. Represent profit values with bars, and indicate targets with a vertical line.
3. Adjust the x-axis ticks to display in thousands.
4. Calculate the percentage of target achievement and visually highlight it using a red-amber-green color scheme.

#### Pie chart

#### Scatter Plot

<hr><hr>